# Generated by Django 2.2 on 2019-04-12 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190412_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cui',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profesion',
            field=models.CharField(choices=[('1', 'Matemático'), ('2', 'Físico')], max_length=1),
        ),
    ]
