# Generated by Django 2.2 on 2019-04-12 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190412_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cui',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profesion',
            field=models.CharField(blank=True, choices=[('1', 'Matemático'), ('2', 'Físico')], max_length=1),
        ),
    ]
