# Generated by Django 2.2 on 2019-04-14 01:30

from django.db import migrations, models
import practica2.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='archivo',
            field=models.FileField(upload_to=practica2.core.models.user_directory_path),
        ),
    ]
