# Generated by Django 2.2 on 2019-04-15 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import practica2.core.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_retrato'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmacionRegistro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=practica2.core.models.random_string, max_length=10)),
                ('validated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
